# Generated by Django 4.2.11 on 2024-06-01 23:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
