# Generated by Django 4.2.11 on 2024-03-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')])),
                ('quote_text', models.TextField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_profession', models.CharField(max_length=100)),
                ('client_image', models.ImageField(upload_to='testimonial_images/')),
            ],
        ),
    ]
